In [ ]:
### DataSet - https://www.kaggle.com/code/jillanisofttech/twitter-us-airline-sentiment-analysis-96-acc/input

In [5]:
import pandas as pd
import numpy as np
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense,Input
from sklearn.model_selection import train_test_split

In [6]:
nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("punkt_tab")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [7]:
df=pd.read_csv("Tweets.csv")

In [8]:
df=df[["text","airline_sentiment"]]

In [9]:
df

                                                    text airline_sentiment
0                    @VirginAmerica What @dhepburn said.           neutral
1      @VirginAmerica plus you've added commercials t...          positive
2      @VirginAmerica I didn't today... Must mean I n...           neutral
3      @VirginAmerica it's really aggressive to blast...          negative
4      @VirginAmerica and it's a really big bad thing...          negative
...                                                  ...               ...
14635  @AmericanAir thank you we got on a different f...          positive
14636  @AmericanAir leaving over 20 minutes Late Flig...          negative
14637  @AmericanAir Please bring American Airlines to...           neutral
14638  @AmericanAir you have my money, you change my ...          negative
14639  @AmericanAir we have 8 ppl so we need 2 know h...           neutral

[14640 rows x 2 columns]

In [10]:
import re
def clean(text):
  text=text.lower()
  text=re.sub(r"http\S+|www\S+|https\S+","",text,flags=re.MULTILINE)
  text=re.sub(r"\@\w+|\#","",text)
  words=text.split()

  words=[word for word in words if word not in stopwords.words("english")]
  lemmatizer=WordNetLemmatizer()
  words=[lemmatizer.lemmatize(word) for word in words]
  return " ".join(words)

In [11]:
df["processed_text"]=df['text'].apply(clean)

In [12]:
df

,text,airline_sentiment,processed_text
0,@VirginAmerica What @dhepburn said.,neutral,said.
1,@VirginAmerica plus you've added commercials t...,positive,plus added commercial experience... tacky.
2,@VirginAmerica I didn't today... Must mean I n...,neutral,today... must mean need take another trip!
3,@VirginAmerica it's really aggressive to blast...,negative,"really aggressive blast obnoxious ""entertainme..."
4,@VirginAmerica and it's a really big bad thing...,negative,really big bad thing
...,...,...,...
14635,@AmericanAir thank you we got on a different f...,positive,thank got different flight chicago.
14636,@AmericanAir leaving over 20 minutes Late Flig...,negative,leaving 20 minute late flight. warning communi...
14637,@AmericanAir Please bring American Airlines to...,neutral,please bring american airline blackberry10
14638,"@AmericanAir you have my money, you change my ...",negative,"money, change flight, answer phones! suggestio..."
14639,@AmericanAir we have 8 ppl so we need 2 know h...,neutral,8 ppl need 2 know many seat next flight. plz p...

In [13]:
tokenize=Tokenizer(num_words=5000)

In [14]:
tokenize.fit_on_texts(df["processed_text"])

In [15]:
len(tokenize.word_counts)

13357

In [16]:
padded=pad_sequences(tokenize.texts_to_sequences(df["processed_text"]),maxlen=50,padding="post",truncating="post")

In [17]:
df['airline_sentiment_reviwed']=df['airline_sentiment'].map({"negative":0,"neutral":1,"positive":2})

In [18]:
df

,text,airline_sentiment,processed_text,airline_sentiment_reviwed
0,@VirginAmerica What @dhepburn said.,neutral,said.,1
1,@VirginAmerica plus you've added commercials t...,positive,plus added commercial experience... tacky.,2
2,@VirginAmerica I didn't today... Must mean I n...,neutral,today... must mean need take another trip!,1
3,@VirginAmerica it's really aggressive to blast...,negative,"really aggressive blast obnoxious ""entertainme...",0
4,@VirginAmerica and it's a really big bad thing...,negative,really big bad thing,0
...,...,...,...,...
14635,@AmericanAir thank you we got on a different f...,positive,thank got different flight chicago.,2
14636,@AmericanAir leaving over 20 minutes Late Flig...,negative,leaving 20 minute late flight. warning communi...,0
14637,@AmericanAir Please bring American Airlines to...,neutral,please bring american airline blackberry10,1
14638,"@AmericanAir you have my money, you change my ...",negative,"money, change flight, answer phones! suggestio...",0
14639,@AmericanAir we have 8 ppl so we need 2 know h...,neutral,8 ppl need 2 know many seat next flight. plz p...,1

In [19]:
model=Sequential()

model.add(Input(shape=(50,)))
model.add(Embedding(5000,128,input_shape=50))
model.add(LSTM(128,return_sequences=True))
model.add(LSTM(64))
model.add(Dense(3,activation="softmax"))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:103: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [20]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 50, 128)        │       640,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 50, 128)        │       131,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 64)             │        49,408 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 3)              │           195 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 821,187 (3.13 MB)

 Trainable params: 821,187 (3.13 MB)

 Non-trainable params: 0 (0.00 B)

In [21]:
model.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics=["accuracy"])

In [22]:
labels=df["airline_sentiment_reviwed"]

In [23]:
history=model.fit(padded,labels,epochs=100,validation_split=0.2)

Epoch 1/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 10s 13ms/step - accuracy: 0.6048 - loss: 0.9457 - val_accuracy: 0.7128 - val_loss: 0.8174
Epoch 2/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.6052 - loss: 0.9405 - val_accuracy: 0.7128 - val_loss: 0.8098
Epoch 3/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.6054 - loss: 0.9425 - val_accuracy: 0.7128 - val_loss: 0.8309
Epoch 4/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.6054 - loss: 0.9420 - val_accuracy: 0.7128 - val_loss: 0.8153
Epoch 5/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.6054 - loss: 0.9421 - val_accuracy: 0.7128 - val_loss: 0.8325
Epoch 6/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.6054 - loss: 0.9420 - val_accuracy: 0.7128 - val_loss: 0.8144
Epoch 7/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - accuracy: 0.6054 - loss: 0.9419 - val_accuracy: 0.7128 - val_loss: 0.8153
Epoch 8/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.6054 - loss: 0.9417 - val_accuracy: 0.7128 - val_loss: 0.8325
Epoch 9/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.6054 - loss: 0.9417 - val_accuracy: 0.7128 - val_loss: 0.8130
Epoch 10/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.6054 - loss: 0.9415 - val_accuracy: 0.7128 - val_loss: 0.8213
Epoch 11/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - accuracy: 0.6054 - loss: 0.9413 - val_accuracy: 0.7128 - val_loss: 0.8403
Epoch 12/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.6054 - loss: 0.9415 - val_accuracy: 0.7128 - val_loss: 0.8256
Epoch 13/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.6054 - loss: 0.9416 - val_accuracy: 0.7128 - val_loss: 0.8310
Epoch 14/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.6054 - loss: 0.9417 - val_accuracy: 0.7128 - val_loss: 0.8217
Epoch 15/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.6054 - loss: 0.9414 - val_accuracy: 0.7128 - val_loss: 0.8170
Epoch 16/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.6054 - loss: 0.9414 - val_accuracy: 0.7128 - val_loss: 0.8221
Epoch 17/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.6054 - loss: 0.9415 - val_accuracy: 0.7128 - val_loss: 0.8140
Epoch 18/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.6054 - loss: 0.9413 - val_accuracy: 0.7128 - val_loss: 0.8195
Epoch 19/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.6054 - loss: 0.9408 - val_accuracy: 0.7128 - val_loss: 0.8093
Epoch 20/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.6052 - loss: 0.9426 - val_accuracy: 0.7128 - val_loss: 0.8192
Epoch 21/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.6054 - loss: 0.9418 - val_accuracy: 0.7128 - val_loss: 0.8261
Epoch 22/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.6054 - loss: 0.9417 - val_accuracy: 0.7128 - val_loss: 0.8111
Epoch 23/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.6054 - loss: 0.9418 - val_accuracy: 0.7128 - val_loss: 0.8294
Epoch 24/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.6054 - loss: 0.9413 - val_accuracy: 0.7128 - val_loss: 0.8219
Epoch 25/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.6054 - loss: 0.9414 - val_accuracy: 0.7128 - val_loss: 0.8201
Epoch 26/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.6054 - loss: 0.9415 - val_accuracy: 0.7128 - val_loss: 0.8159
Epoch 27/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.6062 - loss: 0.9315 - val_accuracy: 0.7186 - val_loss: 0.6861
Epoch 28/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.6612 - loss: 0.7476 - val_accuracy: 0.7732 - val_loss: 0.5824
Epoch 29/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.7649 - loss: 0.5939 - val_accuracy: 0.7869 - val_loss: 0.5420
Epoch 30/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.8238 - loss: 0.4837 - val_accuracy: 0.7896 - val_loss: 0.5342
Epoch 31/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.8638 - loss: 0.3966 - val_accuracy: 0.7927 - val_loss: 0.5407
Epoch 32/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.8884 - loss: 0.3333 - val_accuracy: 0.7930 - val_loss: 0.5820
Epoch 33/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.9099 - loss: 0.2738 - val_accuracy: 0.7917 - val_loss: 0.6177
Epoch 34/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.9305 - loss: 0.2252 - val_accuracy: 0.7889 - val_loss: 0.6386
Epoch 35/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - accuracy: 0.9419 - loss: 0.1893 - val_accuracy: 0.7818 - val_loss: 0.7455
Epoch 36/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.9531 - loss: 0.1598 - val_accuracy: 0.7801 - val_loss: 0.7963
Epoch 37/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.9594 - loss: 0.1380 - val_accuracy: 0.7749 - val_loss: 0.8897
Epoch 38/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.9642 - loss: 0.1183 - val_accuracy: 0.7650 - val_loss: 0.9477
Epoch 39/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.9703 - loss: 0.1026 - val_accuracy: 0.7626 - val_loss: 1.0261
Epoch 40/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.9740 - loss: 0.0937 - val_accuracy: 0.7719 - val_loss: 0.9844
Epoch 41/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.9763 - loss: 0.0841 - val_accuracy: 0.7602 - val_loss: 1.1156
Epoch 42/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.9754 - loss: 0.0837 - val_accuracy: 0.7531 - val_loss: 1.1140
Epoch 43/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.9781 - loss: 0.0758 - val_accuracy: 0.7664 - val_loss: 1.0669
Epoch 44/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.9799 - loss: 0.0693 - val_accuracy: 0.7630 - val_loss: 1.1786
Epoch 45/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.9820 - loss: 0.0610 - val_accuracy: 0.7480 - val_loss: 1.2782
Epoch 46/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.9834 - loss: 0.0565 - val_accuracy: 0.7520 - val_loss: 1.2413
Epoch 47/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.9827 - loss: 0.0566 - val_accuracy: 0.7565 - val_loss: 1.2554
Epoch 48/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.9840 - loss: 0.0514 - val_accuracy: 0.7609 - val_loss: 1.3747
Epoch 49/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.9839 - loss: 0.0551 - val_accuracy: 0.7640 - val_loss: 1.2468
Epoch 50/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.9850 - loss: 0.0477 - val_accuracy: 0.7620 - val_loss: 1.3299
Epoch 51/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.9861 - loss: 0.0459 - val_accuracy: 0.7524 - val_loss: 1.4384
Epoch 52/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.9862 - loss: 0.0432 - val_accuracy: 0.7579 - val_loss: 1.4367
Epoch 53/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 7s 19ms/step - accuracy: 0.9892 - loss: 0.0349 - val_accuracy: 0.7534 - val_loss: 1.5201
Epoch 54/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - accuracy: 0.9900 - loss: 0.0299 - val_accuracy: 0.7524 - val_loss: 1.5259
Epoch 55/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.9873 - loss: 0.0365 - val_accuracy: 0.7466 - val_loss: 1.4691
Epoch 56/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 6s 16ms/step - accuracy: 0.9885 - loss: 0.0349 - val_accuracy: 0.7350 - val_loss: 1.6669
Epoch 57/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 6s 18ms/step - accuracy: 0.9880 - loss: 0.0351 - val_accuracy: 0.7500 - val_loss: 1.5133
Epoch 58/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.9876 - loss: 0.0361 - val_accuracy: 0.7606 - val_loss: 1.5362
Epoch 59/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.9894 - loss: 0.0282 - val_accuracy: 0.7531 - val_loss: 1.6169
Epoch 60/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.9909 - loss: 0.0247 - val_accuracy: 0.7377 - val_loss: 1.9460
Epoch 61/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.9917 - loss: 0.0224 - val_accuracy: 0.7510 - val_loss: 1.7894
Epoch 62/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.9920 - loss: 0.0203 - val_accuracy: 0.7517 - val_loss: 1.9202
Epoch 63/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.9926 - loss: 0.0199 - val_accuracy: 0.7452 - val_loss: 2.0110
Epoch 64/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.9898 - loss: 0.0285 - val_accuracy: 0.7507 - val_loss: 1.7206
Epoch 65/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.9898 - loss: 0.0278 - val_accuracy: 0.7462 - val_loss: 1.7795
Epoch 66/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.9911 - loss: 0.0244 - val_accuracy: 0.7442 - val_loss: 1.8306
Epoch 67/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.9918 - loss: 0.0220 - val_accuracy: 0.7592 - val_loss: 1.7644
Epoch 68/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.9921 - loss: 0.0205 - val_accuracy: 0.7251 - val_loss: 1.9109
Epoch 69/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.9917 - loss: 0.0216 - val_accuracy: 0.7302 - val_loss: 1.8904
Epoch 70/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.9918 - loss: 0.0226 - val_accuracy: 0.7268 - val_loss: 1.7113
Epoch 71/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.9913 - loss: 0.0219 - val_accuracy: 0.7401 - val_loss: 1.9823
Epoch 72/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.9922 - loss: 0.0195 - val_accuracy: 0.7456 - val_loss: 1.8228
Epoch 73/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.9915 - loss: 0.0209 - val_accuracy: 0.7384 - val_loss: 1.9466
Epoch 74/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.9923 - loss: 0.0196 - val_accuracy: 0.7415 - val_loss: 2.1120
Epoch 75/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.9927 - loss: 0.0201 - val_accuracy: 0.7480 - val_loss: 1.9145
Epoch 76/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.9934 - loss: 0.0173 - val_accuracy: 0.7374 - val_loss: 2.0711
Epoch 77/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.9938 - loss: 0.0161 - val_accuracy: 0.7380 - val_loss: 2.1420
Epoch 78/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.9935 - loss: 0.0161 - val_accuracy: 0.7394 - val_loss: 2.0926
Epoch 79/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 5s 15ms/step - accuracy: 0.9935 - loss: 0.0171 - val_accuracy: 0.7411 - val_loss: 1.9871
Epoch 80/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.9932 - loss: 0.0167 - val_accuracy: 0.7544 - val_loss: 2.1242
Epoch 81/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.9924 - loss: 0.0217 - val_accuracy: 0.7500 - val_loss: 1.6689
Epoch 82/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.9886 - loss: 0.0306 - val_accuracy: 0.7520 - val_loss: 1.7669
Epoch 83/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.9926 - loss: 0.0204 - val_accuracy: 0.7486 - val_loss: 1.7959
Epoch 84/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.9935 - loss: 0.0170 - val_accuracy: 0.7336 - val_loss: 1.9552
Epoch 85/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.9938 - loss: 0.0154 - val_accuracy: 0.7343 - val_loss: 2.1923
Epoch 86/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.9928 - loss: 0.0159 - val_accuracy: 0.7377 - val_loss: 2.1626
Epoch 87/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.9934 - loss: 0.0166 - val_accuracy: 0.7387 - val_loss: 1.8996
Epoch 88/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.9938 - loss: 0.0156 - val_accuracy: 0.7394 - val_loss: 2.2117
Epoch 89/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.9934 - loss: 0.0172 - val_accuracy: 0.7329 - val_loss: 2.0809
Epoch 90/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.9930 - loss: 0.0175 - val_accuracy: 0.7264 - val_loss: 2.1935
Epoch 91/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.9930 - loss: 0.0180 - val_accuracy: 0.7367 - val_loss: 2.1696
Epoch 92/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.9927 - loss: 0.0174 - val_accuracy: 0.7380 - val_loss: 2.1762
Epoch 93/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.9924 - loss: 0.0238 - val_accuracy: 0.7510 - val_loss: 1.8568
Epoch 94/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.9924 - loss: 0.0209 - val_accuracy: 0.7585 - val_loss: 1.6708
Epoch 95/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.9925 - loss: 0.0208 - val_accuracy: 0.7322 - val_loss: 1.8932
Epoch 96/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.9936 - loss: 0.0160 - val_accuracy: 0.7449 - val_loss: 1.9684
Epoch 97/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.9936 - loss: 0.0151 - val_accuracy: 0.7428 - val_loss: 2.0240
Epoch 98/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - accuracy: 0.9936 - loss: 0.0164 - val_accuracy: 0.7462 - val_loss: 2.0240
Epoch 99/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - accuracy: 0.9939 - loss: 0.0156 - val_accuracy: 0.7548 - val_loss: 1.9812
Epoch 100/100
366/366 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.9943 - loss: 0.0144 - val_accuracy: 0.7517 - val_loss: 2.0022

In [24]:
text=df["text"][3]

In [26]:
text=clean(text)

In [27]:
text=tokenize.texts_to_sequences([text])

In [28]:
text=pad_sequences(text,maxlen=50,padding="post",truncating="post")

In [30]:
y_pred=model.predict(text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

In [31]:
np.argmax(y_pred,axis=1)

array([0])